[package]
name = "spin-componentize"
version = "0.1.0"

edition = "2021"

[dependencies]
anyhow = "1.0.69"
wasmparser = "0.104.0"
wasm-encoder = "0.26.0"
wit-component = "0.8.2"

[dev-dependencies]
anyhow = "1.0.69"
wasmtime = { version = "7.0.0", features = ["component-model"] }
tokio = { version = "1", features = ["macros", "rt", "fs"] }
spin-abi-conformance = { path = "abi-conformance" }
host = { path = "adapter/host" }
wasi-common = { path = "adapter/wasi-common" }
wasi-cap-std-sync = { path = "adapter/wasi-common/cap-std-sync" }
